### ISSUE TITLE
An error about segmentation.py：ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by GongDianCheng** [vigneshr2306/SegMask-Frustum-PointPillar#1]
Excellent work!
Recently, I learned your work normally, but the following problems occurred during the execution process:
`  File "/home/wj/FusionStudy/SegMask-Frustum-PointPillar/second/data/segmentation.py", line 45, in segmentation_full
    segmentation_output_full, prob_per_pixel_full = inference_segmentor(model, img)
ValueError: not enough values to unpack (expected 2, got 1)`
I looked at how  'inference_segmentor ' is implemented and found that the method only returns a value.
`
    with torch.no_grad():
        result = model(return_loss=False, rescale=True, **data)
    return result
`
How did you solve it? Any advice would be greatly appreciated

**Comment by vigneshr2306** [comment]
We modified the inference_segmentor code from the openMMsegmentation library by searching for the part where the probability values (logits) were computed and returned that as well. We couldn't add that file here since it might be considered as duplicating their library.

**Comment by GongDianCheng** [comment]
> 
Thanks for the recovery, I see.
I am a beginner in 3D object detection, and I am not familiar with related operations. Would you mind sending me the relevant implementation part?
